#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug  1 00:28:10 2021

@author: pedrodsk
"""
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score


previsores = pd.read_csv('entradas_breast.csv') # carregar csv no dataframe
classe = pd.read_csv('saidas_breast.csv') #carregar as saidas

def criarRede():
    model = Sequential()
    model.add(Dense(units=16,activation='relu',kernel_initializer='random_uniform',input_dim=30))
    model.add(Dropout(0.2))
    model.add(Dense(units=16,activation='relu',kernel_initializer='random_uniform'))
    model.add(Dropout(0.2))
    model.add(Dense(units=1, activation='sigmoid'))
    otimizador = keras.optimizers.Adam(learning_rate=0.001, decay = 0.0001, clipvalue=0.5)        
    model.compile(optimizer=otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy'])
    return model

model = KerasClassifier(build_fn= criarRede,
                        epochs = 100,
                        batch_size = 10)

resultados = cross_val_score(estimator = model,
                             X = previsores, y=classe,
                             cv=10, scoring ='accuracy')

media= resultados.mean()
desvio = resultados.std() #valores maior = overfitting
