#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 31 23:35:19 2021

@author: pedrodsk
"""
import numpy as np

def stepFunction(soma): #linearmente separaveis
    if(soma>=1):
        return 1
    return 0

def sigmoidFunction(soma): #problemas de classificação binarias
    return 1 / (1+np.exp(-soma))
    
def tahnFunction(soma): #problemas de classificação
    return (np.exp(soma)- np.exp(-soma)) / (np.exp(soma)+np.exp(-soma))

def reluFunction(soma): #convulacionais e multiplas camadas
    if (soma>=0):
        return soma
    return 0

def linearFunction(soma): #problemas de regressão linear
    return soma

def softmaxFunction(soma): #camada de saida, classificação com mais de duas classes
    return np.exp(soma)/(np.exp(soma).sum())
    
    

step = stepFunction(30)
sig = sigmoidFunction(2.1)
tahn = tahnFunction(2.1)
relu = reluFunction(2.1)
linear = linearFunction(2.1)
soft = softmaxFunction([5.0, 2.0, 1.3])

mean1 = (1-0.3)**2
mean2 = (0-0.020)**2
mean3 = (1-0.890)**2
mean4 = (0-0.320)**2
mean = (mean1+mean2+mean3+mean4)/4